# Generated by Django 5.0.4 on 2025-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], max_length=10)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
