# version: '3.8'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 bms_project.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db 
      - DB_PORT=3306
      - USE_DOCKER=true
      - DOCKER_INTERNAL=true
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    networks:
      - bms_network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ./dbase/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bms_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
    - web
    networks:
    - bms_network
networks:
  bms_network:
    driver: bridge

volumes:
  db_data:
  frontend_node_modules:
  static_volume: {}