# Generated by Django 5.0.4 on 2025-10-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productionbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
