# Generated by Django 5.0.4 on 2025-10-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
